articles/urls.py
from django.urls import path
from .views import article_list, article_detail, article_create_view, article_create_form_view, \
    article_edit_form, article_delete_view

app_name = "articles"

urlpatterns = [
    path('', article_list, name='list'),
    path('article/<slug:slug>/', article_detail, name='detail'),
    path('article/create/', article_create_view, name='create'),
    path('article/create/form/', article_create_form_view, name='create_form'),
    path('article/edit/<int:pk>/', article_edit_form, name='edit'),
    path('article/delete/<int:pk>/', article_delete_view, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace="articles")),
    path('account/', include('accounts.urls', namespace="accounts")),
    path('recipes/', include('recipes.urls', namespace="recipes")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models



class Category(models.Model):
    title = models.CharField(max_length=221)


    def __str__(self):
        return self.title

    # article_set
    @property
    def articles_count(self):
        return self.articles.count()


class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Article(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='articles')
    title = models.CharField(max_length=221)
    slug = models.SlugField(max_length=221, unique=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='articles/')
    body = models.TextField()
    tags = models.ManyToManyField(Tag)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "image", "body"]

    def __init__(self, *args,  **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            "placeholder": "title...",
            "class": 'form-control',
        })
        self.fields['image'].widget.attrs.update({
            "class": 'form-control',
        })
        self.fields['body'].widget.attrs.update({
            "placeholder": 'body..',
            "class": 'form-control',
            "cols": 21,
            "rows": 3
        })

articles/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import Http404, HttpResponseForbidden
from django.contrib import messages
from .models import Article, Category, Tag
from .forms import ArticleForm


def article_list(request):
    object_list = Article.objects.order_by('-id')
    object_list_count = object_list.count()
    categories = Category.objects.all()
    tags = Tag.objects.all()
    q = request.GET.get('q')
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    if cat:
        object_list = object_list.filter(category__title__exact=cat)
    if tag:
        object_list = object_list.filter(tags__title__exact=tag)
    if q:
        object_list = object_list.filter(title__icontains=q)


    paginator = Paginator(object_list, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    ctx = {
        'object_list': page_obj,
        'object_list_count': object_list_count,
        'categories': categories,
        'tags': tags,
    }
    return render(request, 'articles/index.html', ctx)


def article_detail(request, slug):
    if slug == "None":
        return HttpResponseForbidden('The object has no attribute "slug"')
    obj = Article.objects.get(slug=slug)

    ctx = {
        "object": obj
    }
    return render(request, 'articles/detail.html', ctx)


def article_create_view(request):
    # print(request.POST)
    ctx = {"created": False}
    if request.method == "POST":
        title = request.POST.get("title")
        body = request.POST.get("body")
        image = request.FILES.get('image')
        # print(title)
        # print(body)
        obj = Article.objects.create(title=title, body=body, image=image)
        if obj:
            # ctx['created'] = True
            messages.success(request, f'The article "{obj.title}" was successfully created')
            ctx['obj'] = obj
            return redirect(reverse('articles:detail', kwargs={"pk": obj.id}))

    return render(request, 'articles/create.html', ctx)


def article_create_form_view(request):
    form = ArticleForm()
    if request.method == "POST":
        form = ArticleForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save()
            messages.success(request, f'The article "{obj.title}" was successfully created')
            return redirect(reverse("articles:detail", kwargs={"pk": obj.id}))
    ctx = {
        "form": form
    }
    return render(request, 'articles/create_form.html', ctx)


def _article_create_form_view(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save()
        messages.success(request, f'The article "{obj.title}" was successfully created')
        return redirect(reverse("articles:detail", kwargs={"pk": obj.id}))
    ctx = {
        "form": form
    }
    return render(request, 'articles/create_form.html', ctx)


def article_edit_form(request, pk):
    try:
        obj = Article.objects.get(id=pk)
    except Article.DoesNotExist:
        raise Http404

    form = ArticleForm(instance=obj)

    if request.method == "POST":
        form = ArticleForm(data=request.POST, instance=obj, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'The article "{obj.title}" was successfully changed')
            return redirect(reverse("articles:detail", kwargs={"pk": pk}))

    ctx = {
        "form": form,
        "obj": obj,
    }

    return render(request, 'articles/edit.html', ctx)


def article_delete_view(request, pk):
    obj = get_object_or_404(Article, id=pk)
    if request.method == "POST":
        obj.delete()
        messages.error(request, f'The article "{obj.title}" was successfully deleted')
        return redirect('articles:list')
    ctx = {
        "object": obj
    }
    return render(request, 'articles/delete.html', ctx)

templates/articles/create.html
{% extends 'base.html' %}

{% block header %}Article Create{% endblock %}

{% block content %}
<div>
    {% if created %}
        <div>
            <h3>{{ obj.title }}</h3>
            <p>{{ obj.body }}</p>
            <code>{{ obj.created_date }}</code>
        </div>
    {% else %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <p>
                <label for="article_title">
                    <b>Title:</b>
                </label>
            </p>
            <input type="text" name="title" id="article_title" placeholder="title..."  required>
        </div>
        <div>
            <p>
                <label for="image_id"><b>Image:</b></label>
                <input type="file" id="image_id" name="image">
            </p>
        </div>
        <div>
            <p>
                <label for="article_body">
                    <b>Body:</b>
                </label>
            </p>
            <textarea name="body" id="article_body" cols="50" rows="3" placeholder="body..." required></textarea>
        </div>
        <div>
            <p>
                <button type="submit" >Save</button>
            </p>
        </div>

    </form>
    {% endif %}
</div>
{% endblock %}

templates/articles/create_form.html
{% extends 'base.html' %}

{% block header %}Article Create Django Form{% endblock %}

{% block content %}
<div>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <div>
            <p>
                <button type="submit" >Save</button>
            </p>
        </div>

    </form>
</div>
{% endblock %}

templates/articles/delete.html
{% extends 'base.html' %}

{% block header %}Article Delete{% endblock %}

{% block content %}
<div>
    <h3>Are you sure to delete "{{ object.title }}"?</h3>

    <form method="post">
        {% csrf_token %}
        <p>
            <span>
                <a href="{% url 'articles:list' %}" class="btn btn-secondary">Cancel</a>
            </span>
            <span>
               <button type="submit" class="btn btn-danger">Delete</button>
            </span>
        </p>
    </form>

</div>
{% endblock %}

templates/articles/detail.html
{% extends 'base.html' %}

{% block header %}Article Detail{% endblock %}

{% block content %}
<div>
    {% if object.image %}
        <div>
            <img src="{{ object.image.url }}" alt="" style="width: 250px">
        </div>
    {% endif %}
    <h3>{{ object.title }}</h3>
    <p>{{ object.body }}</p>
    <code>
        created_date: {{ object.created_date }}
    </code>
    <br>
    <code>
        modified_date: {{ object.modified_date }}
    </code>

    <div class="mt-3">
        <span>
            <a type="button" class="btn btn-outline-info" href="{% url 'articles:edit' object.id %}">Edit</a>
        </span>
        <span>
            <a type="button" class="btn btn-outline-danger" href="{% url 'articles:delete' object.id %}">Delete</a>
        </span>
    </div>
</div>
{% endblock %}

templates/articles/edit.html
{% extends 'base.html' %}

{% block header %}Article Update Form{% endblock %}

{% block content %}
<div>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <div>
                <button class="btn btn-primary" type="submit">Save</button>
                <a type="button" class="btn btn-secondary" href="{% url 'articles:detail' obj.id %}">Cancel</a>
        </div>

    </form>

</div>
{% endblock %}

templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block header %}Article List{% endblock %}

{% block content %}

    <form method="get" role="search" class="">
        <div class="row justify-content-end">
            <div class="col-4">
                <input class="form-control" autocomplete="off" type="search" placeholder="search..." name="q">
            </div>
            <div class="col-1">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    <div class="row mt-4">
        <div class="col-md-3 p-3">
            <h3>Categories</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="?cat=" class="text-decoration-none">All<span
                            class="badge text-bg-secondary">{{ object_list_count }}</span></a>
                </li>
                {% for category in categories %}
                    <li class="list-group-item">
                        <a href="?cat={{ category.title }}" class="text-decoration-none">{{ category.title }}<span
                                class="badge text-bg-secondary">{{ category.articles_count }}</span></a>
                    </li>
                {% endfor %}
            </ul>
            <h3>Tags</h3>
            {% for tag in tags %}
                <span class="badge text-bg-dark">
                    <a href="?tag={{ tag.title }}" class="text-light text-decoration-none">{{ tag.title }}</a>
                </span>
            {% endfor %}

        </div>

        <div class="col-md-9">
            <div class="row">
                {% if not object_list %}
                    <h1>Nothing found</h1>
                {% endif %}
                {% for object in object_list %}
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 p-3">
                        <div class="card">
                            {% if object.image %}
                                <img src="{{ object.image.url }}" class="card-img-top" alt="">
                            {% else %}
                                <img src="{% static 'image/noimg.png' %}" class="card-img-top" alt="...">
                            {% endif %}

                            <div class="card-body">
                                <h3 class="card-title"><a href="{% url 'articles:detail' object.slug %}"
                                                          class="text-dark nav-link link-offset-1-hover">{{ object.title }}</a>
                                </h3>
                                <code>{{ object.category }}</code>
                                <p class="card-text">{{ object.body|slice:"25" }}...</p>
                                <div class="mb-3">
                                    {% for tag in object.tags.all %}
                                        <span class="mb-2">
                                            <a href="">#{{ tag.title }}</a>
                                        </span>
                                    {% endfor %}

                                </div>
                                <a href="{% url 'articles:edit' object.id %}" class="btn btn-outline-info">edit</a>
                                <a href="{% url 'articles:delete' object.id %}"
                                   class="btn btn-outline-danger">delete</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {% include 'articles/paginator.html' %}

        </div>




    </div>
{% endblock %}

templates/articles/paginator.html
<nav aria-label="">
    <ul class="pagination">
        {% if object_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ object_list.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
        {% endif %}

        {% for i in object_list.paginator.page_range %}
            {% if i == object_list.number %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ i }}</span>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if object_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ object_list.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
        {% endif %}

    </ul>
</nav>