accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
]

articles/urls.py
from django.urls import path
from .views import article_list, article_detail, article_create_view, article_create_form_view, \
    article_edit_form, article_delete_view

app_name = "articles"

urlpatterns = [
    path('', article_list, name='list'),
    path('article/<slug:slug>/', article_detail, name='detail'),
    path('article/create/', article_create_view, name='create'),
    path('article/create/form/', article_create_form_view, name='create_form'),
    path('article/edit/<int:pk>/', article_edit_form, name='edit'),
    path('article/delete/<int:pk>/', article_delete_view, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace="articles")),
    path('account/', include('accounts.urls', namespace="accounts")),
    path('recipes/', include('recipes.urls', namespace="recipes")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipes_list, recipe_create, recipe_detail, recipe_edit, recipe_delete,\
    ingredient_create, ingredient_edit, ingredient_delete


app_name = 'recipes'

urlpatterns = [
    path('', recipes_list, name='list'),
    path('create/', recipe_create, name='create'),
    path('detail/<int:pk>/', recipe_detail, name='detail'),
    path('edit/<int:pk>/', recipe_edit, name='edit'),
    path('delete/<int:pk>/', recipe_delete, name='delete'),

    path('<int:recipe_id>/ingredienet/create/', ingredient_create, name='ing_create'),
    path('<int:recipe_id>/ingredienet/edit/<int:pk>/', ingredient_edit, name='ing_edit'),
    path('<int:recipe_id>/ingredienet/delete/<int:pk>/', ingredient_delete, name='ing_delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Trydjango{% endblock %}</title>
    {#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">#}
    <link rel="stylesheet" href="{% static 'bootstrap_5_3_0/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
{% include 'header.html' %}

<div class="messages show" id="messages">

    {% for message in messages %}
        {% if 'success' in message.tags %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
        {% elif 'error' in message.tags %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% elif 'info' in message.tags %}
            <div class="alert alert-primary" role="alert">{{ message }}</div>
        {% elif 'warning' in message.tags %}
            <div class="alert alert-warning" role="alert">{{ message }}</div>
        {% endif %}
    {% endfor %}

</div>

<div class="container mt-4">
    {% block content %}

    {% endblock %}
</div>

{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>#}
<script src="{% static 'bootstrap_5_3_0/js/bootstrap.bundle.min.js' %}"></script>

<script>
    setTimeout(function () {
        var element = document.getElementById('messages');
        if (element.classList.contains('show')) {
            element.classList.remove('show');
            element.classList.add('hide');
        }
    }, 3000);
</script>

</body>
</html>

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'articles:list' %}">
            <img class="logo_img" src="{% static 'image/isystem-logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'articles:list' %}">Articles</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Article add
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'articles:create' %}">Simple add</a></li>
                        <li><a class="dropdown-item" href="{% url 'articles:create_form' %}">Django form add</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'recipes:list' %}">Recipes</a>
                </li>
            </ul>
            <div class="d-flex" >
                    {% if request.user.is_authenticated %}
                        {{ request.user.username }} /
                        <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
                    {% else %}

                        <a href="{% url 'accounts:login' %}" class="">Login </a> /
                        <a href="{% url 'accounts:register' %}" class=" ml-2"> Register</a>
                    {% endif %}
            </div>
        </div>
    </div>
</nav>