config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace="articles")),
    path('account/', include('accounts.urls', namespace="accounts")),
    path('recipes/', include('recipes.urls', namespace="recipes")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipes_list, recipe_create, recipe_detail, recipe_edit, recipe_delete,\
    ingredient_create, ingredient_edit, ingredient_delete


app_name = 'recipes'

urlpatterns = [
    path('', recipes_list, name='list'),
    path('create/', recipe_create, name='create'),
    path('detail/<int:pk>/', recipe_detail, name='detail'),
    path('edit/<int:pk>/', recipe_edit, name='edit'),
    path('delete/<int:pk>/', recipe_delete, name='delete'),

    path('<int:recipe_id>/ingredienet/create/', ingredient_create, name='ing_create'),
    path('<int:recipe_id>/ingredienet/edit/<int:pk>/', ingredient_edit, name='ing_edit'),
    path('<int:recipe_id>/ingredienet/delete/<int:pk>/', ingredient_delete, name='ing_delete'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from articles.models import Tag


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    description = models.TextField()
    tags = models.ManyToManyField(Tag)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def get_ingredients_count(self):
        return self.ingredients.count()

    def get_tags_count(self):
        return self.tags.count()

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    UNIT = (
        (0, "gram"),
        (1, "kilogram"),
        (2, "liter"),
        (3, "retail"),
        (4, "teaspoon"),
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    title = models.CharField(max_length=221)
    quantity = models.IntegerField()
    unit = models.IntegerField(choices=UNIT)

    def __str__(self):
        return self.title

recipes/forms.py
from django import forms

from .models import Recipe, Ingredient


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = ['title', 'description', 'tags']
        exclude = ['author']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'rows': 2
        })
        self.fields['tags'].widget.attrs.update({
            'class': 'form-control'
        })



class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['recipe', 'title', 'quantity', 'unit']
        exclude = ['recipe']

    def clean_title(self):  # clean_{field_name}
        title = self.data.get('title')
        if not title[0].isupper():
            raise forms.ValidationError("first character must be uppercase")
        return self.data.get('title')

    def __init__(self, *args, **kwargs):
        super(IngredientForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Ingredient'
        })
        self.fields['quantity'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'example: 300'
        })
        self.fields['unit'].widget.attrs.update({
            'class': 'form-control',
        })

recipes/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages

from .models import Recipe, Ingredient, Tag
from .forms import RecipeForm, IngredientForm
from .permissions import is_owner_to_recipe_decorator, is_owner_to_ing_decorator


def recipes_list(request):
    recipes = Recipe.objects.order_by('-id')
    tags = Tag.objects.all()
    tag = request.GET.get('tag')
    if tag:
        recipes = recipes.filter(tags__title__exact=tag)

    ctx = {
        'object_list': recipes,
        'tags': tags,
    }
    return render(request, 'recipes/list.html', ctx)


@login_required()
def recipe_create(request):
    # if not request.user.is_authenticated:
    #     next_path = request.path
    #     full_path = f"{reverse('accounts:login')}?next={next_path}"
    #     return redirect(full_path)
    form = RecipeForm(request.POST or None)
    user = request.user
    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = user
        obj.save()
        form.save_m2m()
        return redirect('recipes:list')
    ctx = {
        'form': form
    }
    return render(request, 'recipes/create.html', ctx)


def recipe_detail(request, pk):
    obj = get_object_or_404(Recipe, id=pk)
    ctx = {
        'object': obj,
    }
    return render(request, 'recipes/detail.html', ctx)


@login_required()
@is_owner_to_recipe_decorator
def recipe_edit(request, pk):
    obj = get_object_or_404(Recipe, id=pk)
    form = RecipeForm(instance=obj)
    if request.method == 'POST':
        form = RecipeForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            messages.success(request, f'Recipe object "{obj.title}" is changed')
            return redirect(reverse('recipes:detail', kwargs={"pk": pk}))
    ctx = {
        'form': form
    }
    return render(request, 'recipes/edit.html', ctx)


@is_owner_to_recipe_decorator
def recipe_delete(request, pk):
    obj = get_object_or_404(Recipe, id=pk)
    model_meta = Recipe._meta
    related_fields = [
        {'name': field.name, 'objects': field.related_model.objects.filter(recipe=obj)}
        for field in model_meta.get_fields()
        if (field.one_to_many or field.one_to_one or field.many_to_many)
    ]

    if request.method == "POST":
        obj.delete()
        messages.error(request, f'Recipe object "{obj.title}" is deleted')
        return redirect('recipes:list')
    ctx = {
        'object': obj,
        'related_fields': related_fields,
    }
    return render(request, 'recipes/delete.html', ctx)


def ingredient_create(request, recipe_id):
    form = IngredientForm()
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.recipe_id = recipe_id
            obj.save()
            messages.success(request, f'Successfully added new ingredient {obj.title}')
            return redirect(reverse('recipes:detail', kwargs={"pk": recipe_id}))
    ctx = {
        'form': form,
        'recipe_id': recipe_id,
    }
    return render(request, 'recipes/ing/create.html', ctx)


@login_required
@is_owner_to_ing_decorator
def ingredient_edit(request, recipe_id, pk):
    obj = get_object_or_404(Ingredient, id=pk)
    form = IngredientForm(instance=obj)
    if request.method == 'POST':
        form = IngredientForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            messages.success(request, f'Successfully change ingredint "{obj.title}"')
            return redirect(reverse('recipes:detail', kwargs={'pk': recipe_id}))
    ctx = {
        'object': obj,
        'form': form,
        'recipe_id': recipe_id
    }
    return render(request, 'recipes/ing/create.html', ctx)


@login_required
@is_owner_to_ing_decorator
def ingredient_delete(request, **kwargs):
    obj = get_object_or_404(Ingredient, id=kwargs.get('pk'))
    if request.method == 'POST':
        obj.delete()
        messages.error(request, f'Successfully deleted ingredient "{obj.title}"')
        return redirect(reverse('recipes:detail', kwargs={'pk': kwargs.get('recipe_id')}))
    ctx = {
        'object': obj,
        "url_kwargs": kwargs
    }
    return render(request, 'recipes/ing/delete.html', ctx)

templates/recipes/create.html
{% extends 'base.html' %}



{% block content %}

    <div class="row mt-4">
        <div class="col-md-6 offset-md-3">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/recipes/delete.html
{% extends 'base.html' %}


{% block content %}

    <div class="row">
        <div class="col-md-12">
            <form method="post">
                {% csrf_token %}

                <h3 class="text-secondary">Are you sure to delele "{{ object.title }}"?</h3>
                <p>Are you sure you want to delete the selected recipe? All of the following objects and their related
                    items will be deleted:</p>
                <h3 class="mt-3"><strong>Summary</strong></h3>
                <ul>
                    {% for related_field in related_fields %}
                        <li>{{ related_field.name }}: {{ related_field.objects.count }}</li>
                    {% endfor %}

                </ul>
                <h3 class="mt-3"><strong>Objects</strong></h3>
                <ul>
                    {% for related_field in related_fields %}
                        {% for object in related_field.objects %}
                            <li>{{ related_field.name }}: {{ object }}</li>
                        {% endfor %}

                    {% endfor %}
                </ul>
                <button class="btn btn-danger mt-3" type="submit">Yes, i'm sure</button>
                <a class="btn btn-secondary mt-3" href="{% url 'recipes:detail' object.id %}">No, take me back</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/recipes/detail.html
{% extends 'base.html' %}

{% block header %}Recipe Detail{% endblock %}

{% block content %}
    <div>
        <h3>{{ object.title }}</h3>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{ object.author }}</h6>
        <p>{{ object.description }}</p>
        <code>
            created_date: {{ object.created_date }}
        </code>
        <br>
        <code>
            modified_date: {{ object.modified_date }}
        </code>
        {% if request.user == object.author %}
        <div class="mt-3">
            <span>
                <a type="button" class="btn btn-outline-info" href="{% url 'recipes:edit' object.id %}">Edit</a>
            </span>
                <span>
                <a type="button" class="btn btn-outline-danger" href="{% url 'recipes:delete' object.id %}">Delete</a>
            </span>
        </div>
        {% endif %}
    </div>
    <div class="row mt-4">
        <h2>
            Ingredients
            {% if request.user == object.author %}
            <a href="{% url 'recipes:ing_create' object.id %}" class="btn d-inline-grid btn-primary">+ Add New
                Ingredient</a>
            {% endif %}
        </h2>

        <hr>
        {% for i in object.ingredients.all %}
            <div class="col-md-3 mt-2">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-body-secondary">{{ i.title }}</h6>
                        <p class="card-text">Quantity: {{ i.quantity }} {{ i.get_unit_display }}</p>
                        {% if request.user == object.author %}
                            <a href="{% url 'recipes:ing_edit' object.id i.id %}" class="card-link ">Edit</a>
                            <a href="{% url 'recipes:ing_delete' object.id i.id %}" class="card-link ">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/recipes/edit.html
{% extends 'base.html' %}


{% block content %}

    <div class="row mt-4">
        <div class="col-md-6 offset-md-3">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/recipes/list.html
{% extends 'base.html' %}
{% block header %}Article List{% endblock %}

{% block content %}

    <div class="row mt-4">
        <div class="col-md-3 p-3">
            <div class="d-grid gap-2 mb-3">
                <a class="btn btn-primary" href="{% url 'recipes:create' %}" type="button">+ Recipe</a>
            </div>
            <h3>Tags</h3>
            <span class="badge text-bg-dark">
                    <a href="." class="text-light text-decoration-none">all</a>
                </span>
            {% for tag in tags %}
                <span class="badge text-bg-dark">
                    <a href="?tag={{ tag.title }}" class="text-light text-decoration-none">{{ tag.title }}</a>
                </span>
            {% endfor %}

        </div>

        <div class="col-md-9">
            <div class="row">
                {% if not object_list %}
                    <h1>Nothing found</h1>
                {% endif %}
                {% for object in object_list %}
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 p-3">
                        <div class="card">
                            <div class="card-body">
                                <h3 class="card-title"><a href="{% url 'recipes:detail' object.id %}"
                                                          class="text-dark nav-link link-offset-1-hover">{{ object.title }}</a>
                                </h3>
                                <h6 class="card-subtitle mb-2 text-body-secondary">{{ object.author }}</h6>
                                <code>{{ object.category }}</code>
                                <p class="card-text">{{ object.description|slice:"25" }}...</p>
                                <div class="mb-3">
                                    {% for tag in object.tags.all %}
                                        <span class="mb-2">
                                            <a href="">#{{ tag.title }}</a>
                                        </span>
                                    {% endfor %}

                                </div>

                                <a href="{% url 'recipes:edit' object.id %}" class="btn btn-outline-info {% if request.user != object.author %}disabled{% endif %}">edit</a>
                                <a href="{% url 'recipes:delete' object.id %}"
                                   class="btn btn-outline-danger {% if request.user != object.author %}disabled{% endif %}">delete</a>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}